"""Ajout complet des entites metier

Revision ID: 82e4b2a81c0e
Revises: 
Create Date: 2026-07-20 19:59:27.398839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e4b2a81c0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_centers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('urgence_24h', sa.Boolean(), nullable=True),
    sa.Column('horaires', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pharmacies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('garde', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone')
    )
    op.create_table('emergency_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('lien_parente', sa.String(length=100), nullable=True),
    sa.Column('priorite', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('first_aid_sheets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('symptomes', sa.Text(), nullable=True),
    sa.Column('gestes_a_faire', sa.Text(), nullable=True),
    sa.Column('gestes_interdits', sa.Text(), nullable=True),
    sa.Column('quand_consulter', sa.Text(), nullable=True),
    sa.Column('illustration_url', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_center_services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('health_center_id', sa.String(length=36), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['health_center_id'], ['health_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('first_aid_recommended_centers',
    sa.Column('first_aid_sheet_id', sa.String(length=36), nullable=False),
    sa.Column('health_center_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['first_aid_sheet_id'], ['first_aid_sheets.id'], ),
    sa.ForeignKeyConstraint(['health_center_id'], ['health_centers.id'], ),
    sa.PrimaryKeyConstraint('first_aid_sheet_id', 'health_center_id')
    )
    op.create_table('sos_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type_urgence', sa.String(length=50), nullable=False),
    sa.Column('type_centre_souhaite', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('contact_urgence_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_urgence_id'], ['emergency_contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sos_alerts')
    op.drop_table('first_aid_recommended_centers')
    op.drop_table('health_center_services')
    op.drop_table('first_aid_sheets')
    op.drop_table('emergency_contacts')
    op.drop_table('users')
    op.drop_table('pharmacies')
    op.drop_table('health_centers')
    # ### end Alembic commands ###
